// Initialisation

export const MARK_REFRESH_STATE = "MARK_REFRESH_STATE";
export const INIT_USERS = "INIT_USERS";
export const INIT_DATAFILES = "INIT_DATAFILES";
export const INIT_METADATA = "INIT_METADATA";
export const INIT_PEOPLE = "INIT_PEOPLE";
export const INIT_LN_ABSENCES = "INIT_LN_ABSENCES";
export const INIT_HRA_ABSENCES = "INIT_HRA_ABSENCES";

// Manager Authentication Actions

export const SIGNIN_SHOWMODAL = "SIGNIN_SHOWMODAL";
export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNIN_CLOSEMODAL = "SIGNIN_CLOSEMODAL";

export const SIGNUP_SHOWMODAL = "SIGNUP_SHOWMODAL";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_CLOSEMODAL = "SIGNUP_CLOSEMODAL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_TOKEN = "SET_TOKEN";

// Manage Error Actions

export const ERROR_SHOW = "ERROR_SHOW";
export const ERROR_CLOSE = "ERROR_CLOSE";

// Manage Users Actions
export const USERS_LIST_START = "USERS_LIST_START";
export const USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS";
export const USERS_LIST_FAIL = "USERS_LIST_FAIL";
export const USER_LIST_MUST_BE_UPDATED = "USER_LIST_MUST_BE_UPDATED";
export const USER_SHOW = "USER_SHOW";
export const USER_HIDE = "USER_HIDE";
export const USER_MODE_VIEW = "USER_MODE_VIEW";
export const USER_MODE_EDIT = "USER_MODE_EDIT";
export const USER_DELETE_START = "USER_DELETE_START";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_SAVE_START = "USER_SAVE_START";
export const USER_SAVE_SUCCESS = "USER_SAVE_SUCCESS";
export const USER_SAVE_FAIL = "USER_SAVE_FAIL";

// Manage People Actions
export const PEOPLE_LIST_START = "PEOPLE_LIST_START";
export const PEOPLE_LIST_SUCCESS = "PEOPLE_LIST_SUCCESS";
export const PEOPLE_LIST_FAIL = "PEOPLE_LIST_FAIL";
export const PEOPLE_LIST_MUST_BE_UPDATED = "PEOPLE_LIST_MUST_BE_UPDATED";
export const PEOPLE_SHOW = "PEOPLE_SHOW";
export const PEOPLE_HIDE = "PEOPLE_HIDE";
export const PEOPLE_MODE_VIEW = "PEOPLE_MODE_VIEW";
export const PEOPLE_MODE_EDIT = "PEOPLE_MODE_EDIT";
export const PEOPLE_DELETE_START = "PEOPLE_DELETE_START";
export const PEOPLE_DELETE_SUCCESS = "PEOPLE_DELETE_SUCCESS";
export const PEOPLE_DELETE_FAIL = "PEOPLE_DELETE_FAIL";
export const PEOPLE_SAVE_START = "PEOPLE_SAVE_START";
export const PEOPLE_SAVE_SUCCESS = "PEOPLE_SAVE_SUCCESS";
export const PEOPLE_SAVE_FAIL = "PEOPLE_SAVE_FAIL";

// Manage Generic Actions
// MetaData
export const READ_METADATA = "READ_METADATA";
export const LOAD_METADATA_START = "LOAD_METADATA_START";
export const LOAD_METADATA_SUCCESS = "LOAD_METADATA_SUCCESS";
export const LOAD_METADATA_FAIL = "LOAD_METADATA_FAIL";
export const SAVE_METADATA_START = "SAVE_METADATA_START";
export const SAVE_METADATA_SUCCESS = "SAVE_METADATA_SUCCESS";
export const SAVE_METADATA_FAIL = "SAVE_METADATA_FAIL";
// DataFile
export const READ_DATAFILE = "READ_DATAFILE";
export const LOAD_DATAFILE_START = "LOAD_DATAFILE_START";
export const LOAD_DATAFILE_SUCCESS = "LOAD_DATAFILE_SUCCESS";
export const LOAD_DATAFILE_FAIL = "LOAD_DATAFILE_FAIL";
export const SAVE_DATAFILE_START = "SAVE_DATAFILE_START";
export const SAVE_DATAFILE_SUCCESS = "SAVE_DATAFILE_SUCCESS";
export const SAVE_DATAFILE_FAIL = "SAVE_DATAFILE_FAIL";
export const DELETE_DATAFILE_START = "DELETE_DATAFILE_START";
export const DELETE_DATAFILE_SUCCESS = "DELETE_DATAFILE_SUCCESS";
export const DELETE_DATAFILE_FAIL = "DELETE_DATAFILE_FAIL";
// Manage Socket Subscription

export const LNCHANNEL_JOIN = "LNCHANNEL_JOIN";
export const LNCHANNEL_LEAVE = "LNCHANNEL_LEAVE";

// Manage Absences

export const HRA_ABS_SAVE_START = "HRA_ABS_SAVE_START";
export const HRA_ABS_BULK_SAVE_START = "HRA_ABS_BULK_SAVE_START";
export const HRA_ABS_SAVE_SUCCESS = "HRA_ABS_SAVE_SUCCESS";
export const HRA_ABS_BULK_SAVE_SUCCESS = "HRA_ABS_BULK_SAVE_SUCCESS";
export const HRA_ABS_SAVE_FAIL = "HRA_ABS_SAVE_FAIL";
export const HRA_ABS_BULK_SAVE_FAIL = "HRA_ABS_BULK_SAVE_FAIL";
export const HRA_ABS_LIST_START = "HRA_ABS_LIST_START";
export const HRA_ABS_LIST_SUCCESS = "HRA_ABS_LIST_SUCCESS";
export const HRA_ABS_LIST_FAIL = "HRA_ABS_LIST_FAIL";

export const LN_ABS_SAVE_START = "LN_ABS_SAVE_START";
export const LN_ABS_BULK_SAVE_START = "LN_ABS_BULK_SAVE_START";
export const LN_ABS_SAVE_SUCCESS = "LN_ABS_SAVE_SUCCESS";
export const LN_ABS_BULK_SAVE_SUCCESS = "LN_ABS_BULK_SAVE_SUCCESS";
export const LN_ABS_SAVE_FAIL = "LN_ABS_SAVE_FAIL";
export const LN_ABS_BULK_SAVE_FAIL = "LN_ABS_BULK_SAVE_FAIL";
export const LN_ABS_LIST_START = "LN_ABS_LIST_START";
export const LN_ABS_LIST_SUCCESS = "LN_ABS_LIST_SUCCESS";
export const LN_ABS_LIST_FAIL = "LN_ABS_LIST_FAIL";

export const ANOMALIES_ANALYSE_START = "ANOMALIES_ANALYSE_START";
export const ANOMALIES_ANALYSE_SUCCESS = "ANOMALIES_ANALYSE_SUCCESS";
export const ANOMALIES_ANALYSE_FAIL = "ANOMALIES_ANALYSE_FAIL";
export const ANOMALIES_LIST_START = "ANOMALIES_LIST_START";
export const ANOMALIES_LIST_SUCCESS = "ANOMALIES_LIST_SUCCESS";
export const ANOMALIES_LIST_FAIL = "ANOMALIES_LIST_FAIL";
export const ANOMALIE_UPDATE_START = "ANOMALIE_UPDATE_START";
export const ANOMALIE_UPDATE_SUCCESS = "ANOMALIE_UPDATE_SUCCESS";
export const ANOMALIE_UPDATE_FAIL = "ANOMALIE_UPDATE_FAIL";
export const ANOMALIES_CLEAR = "ANOMALIES_CLEAR";
